name: cs-strapi cms to Azure Web App - collapse-survivor-cms-webapp-dev

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Select the environment to deploy to'
        options:
          - dev
          - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip awt-app-release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: awt-app-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.event.inputs.choice }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: unzip artifact for deployment
        run: unzip awt-app-release.zip

      - name: Clean awt-app-release zip file
        run: |
          rm -f awt-app-release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.event.inputs.choice == 'dev' && 'collapse-survivor-cms-webapp-dev' || 'collapse-survivor-cms-webapp-staging' }}
          slot-name: 'Production'  # Use the same slot name for both environments
          publish-profile: ${{ github.event.inputs.choice == 'dev' && secrets.AZUREAPPSERVICE_PUBLISHPROFILE_89DE5ADCFA1642148BA04B17D6041BD0 || secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
